version: 0.2

phases:
  install:
    commands:
      - echo "Installing required packages..."
      - go get -u github.com/stretchr/testify
  pre_build:
    commands:
      - echo "Running tests..."
      - go test -coverprofile=coverage.out
  build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Building the Docker image..."
      - docker build -t another-simple-api .
      - echo "Tagging the Docker image..."
      - docker tag another-simple-api:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/another-simple-api:latest
      - echo "Pushing the Docker image..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/another-simple-api:latest

artifacts:
  files:
    - Dockerfile
    - coverage.out

reports:
  test-coverage: # Test coverage report
    file-format: COBERTURAXML
    files:
      - coverage.out
    base-directory: '.'